[[obtaining]]
== 获得 Hibernate

=== THibernate 的模块/包（modules/artifacts）

Hibernate 的功能被拆分成一系列的模块/包（modules/artifacts），其目的是为了对依赖进行独立（模块化）。

hibernate-core:: 这个是 Hibernate 的主要（main (core)）模块。定义了 ORM 的特性和 API 以及一系列整合的 SPIs。
hibernate-envers:: Hibernate 历史的实体版本特性
hibernate-spatial:: Hibernate 的 Spatial/GIS 数据类型支持
hibernate-osgi:: Hibernate 支持运行 OSGi 容器
hibernate-agroal:: 整合 http://agroal.github.io/[Agroal] 连接池库到 Hibernate
hibernate-c3p0:: 整合 http://www.mchange.com/projects/c3p0/[C3P0] 连接池库到 Hibernate
hibernate-hikaricp:: 整合 http://brettwooldridge.github.io/HikariCP/[HikariCP] 连接池库到 Hibernate
hibernate-vibur:: 整合 http://www.vibur.org/[Vibur DBCP] 连接池库到 Hibernate
hibernate-proxool:: 整合 http://proxool.sourceforge.net/[Proxool] 连接池库到 Hibernate
hibernate-jcache:: 整合 https://jcp.org/en/jsr/detail?id=107$$[JCache] 缓存特性到 Hibernate，使任何与其兼容的缓存实现能够成为 Hibernate 二级缓存的提供者
hibernate-ehcache:: 整合 http://ehcache.org/[Ehcache] 缓存库到 Hibernate 中成为 Hibernate 的二级缓存提供者

=== 发行组件下载

Hibernate 项目小组提供了一系列发布组合（bundles），这些发布组合发布在 SourceForge 文件发布系统中。这些发布的包有
`TGZ` 和 `ZIP` 格式。每一个发布组合包含有 `JAR` 文件，文档，源代码和其他一些有用的内容。

你可以选择你需要的格式来下载 Hibernate 的发布版本，有关发布版本的列表，请参考
https://sourceforge.net/projects/hibernate/files/hibernate-orm/.  发布版本的结构请参考下面的内容：

*  `lib/required/` 目录包含有 `hibernate-core` Jar 和所有需要的依赖。不管你需要使用 Hibernate 的何种功能，所有的这些都需要设置到你的  classpath 路径中
*  `lib/envers` 目录包含有 `hibernate-envers` Jar 和需要的依赖（这些依赖，不包含在 `lib/required/` 和 `lib/jpa/` 中）
*  `lib/spatial/` 目录包含有 `hibernate-spatial` Jar 和需要的依赖（这些依赖，不包含在 lib/required/ 和lib/jpa/ 中）
*  `lib/osgi/` 目录包含有 `hibernate-osgi`  Jar 和需要的依赖（这些依赖，不包含在 lib/required/ 和lib/jpa/ 中）
*  `lib/jpa-metamodel-generator/` 目录包含了创建 Criteria API type-safe 元模型（Metamodel）所需要的 Jar
*  `lib/optional/` 包含了各个连接池和 Hibernate 提供的二级缓存所需要的 Jar，已经它们所需要的依赖

=== Maven Repository Artifacts

The authoritative repository for Hibernate artifacts is the JBoss Maven repository.  The Hibernate artifacts are
synced to Maven Central as part of an automated job (some small delay may occur).

The team responsible for the JBoss Maven repository maintains a number of Wiki pages that contain important information:

* http://community.jboss.org/docs/DOC-14900 - General information about the repository.
* http://community.jboss.org/docs/DOC-15170 - Information about setting up the JBoss repositories in order to do
development work on JBoss projects themselves.
* http://community.jboss.org/docs/DOC-15169 - Information about setting up access to the repository to use JBoss
projects as part of your own software.

The Hibernate ORM artifacts are published under the `org.hibernate` groupId.
