[[obtaining]]
== 获得 Hibernate

=== THibernate 的模块/包（modules/artifacts）

Hibernate 的功能被拆分成一系列的模块/包（modules/artifacts），其目的是为了对依赖进行独立（模块化）。

hibernate-core:: 这个是 Hibernate 的主要（main (core)）模块。定义了 ORM 的特性和 API 以及一系列整合的 SPIs。
hibernate-envers:: Hibernate 历史的实体版本特性
hibernate-spatial:: Hibernate 的 Spatial/GIS 数据类型支持
hibernate-osgi:: Hibernate 支持运行 OSGi 容器
hibernate-agroal:: 整合 http://agroal.github.io/[Agroal] 连接池库到 Hibernate
hibernate-c3p0:: 整合 http://www.mchange.com/projects/c3p0/[C3P0] 连接池库到 Hibernate
hibernate-hikaricp:: 整合 http://brettwooldridge.github.io/HikariCP/[HikariCP] 连接池库到 Hibernate
hibernate-vibur:: 整合 http://www.vibur.org/[Vibur DBCP] 连接池库到 Hibernate
hibernate-proxool:: 整合 http://proxool.sourceforge.net/[Proxool] 连接池库到 Hibernate
hibernate-jcache:: 整合 https://jcp.org/en/jsr/detail?id=107$$[JCache] 缓存特性到 Hibernate，使任何与其兼容的缓存实现能够成为 Hibernate 二级缓存的提供者
hibernate-ehcache:: 整合 http://ehcache.org/[Ehcache] 缓存库到 Hibernate 中成为 Hibernate 的二级缓存提供者

=== Release Bundle Downloads

The Hibernate team provides release bundles hosted on the SourceForge File Release System, in both
`TGZ` and `ZIP` formats.  Each release bundle contains `JAR` files, documentation, source code, and other goodness.

You can download releases of Hibernate, in your chosen format, from the list at
https://sourceforge.net/projects/hibernate/files/hibernate-orm/.  The release bundle is structured as follows:

* The `lib/required/` directory contains the `hibernate-core` jar and all of its dependencies.  All of these jars are
required to be available on your classpath no matter which features of Hibernate are being used.
* The `lib/envers` directory contains the `hibernate-envers` jar and all of its dependencies (beyond those in
`lib/required/` and `lib/jpa/`).
* The `lib/spatial/` directory contains the `hibernate-spatial` jar and all of its dependencies (beyond those in `lib/required/`)
* The `lib/osgi/` directory contains the `hibernate-osgi` jar and all of its dependencies (beyond those in `lib/required/` and `lib/jpa/`)
* The `lib/jpa-metamodel-generator/` directory contains the jar needed for generating the Criteria API type-safe Metamodel.
* The `lib/optional/` directory contains the jars needed for the various connection pooling and second-level cache integrations
provided by Hibernate, along with their dependencies.

=== Maven Repository Artifacts

The authoritative repository for Hibernate artifacts is the JBoss Maven repository.  The Hibernate artifacts are
synced to Maven Central as part of an automated job (some small delay may occur).

The team responsible for the JBoss Maven repository maintains a number of Wiki pages that contain important information:

* http://community.jboss.org/docs/DOC-14900 - General information about the repository.
* http://community.jboss.org/docs/DOC-15170 - Information about setting up the JBoss repositories in order to do
development work on JBoss projects themselves.
* http://community.jboss.org/docs/DOC-15169 - Information about setting up access to the repository to use JBoss
projects as part of your own software.

The Hibernate ORM artifacts are published under the `org.hibernate` groupId.
